nelmio_api_doc:
    documentation:
        servers:
          - url: https://back.globaloutdoor.ci
            description: API over HTTP
          - url: https://back.globaloutdoor.ci
            description: API over HTTPS
        info:
            title: GLOBAL 
            description: This is an awesome app!
            version: 1.0.0
            x-build: #CommitHash
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []