security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        
    providers:
        # Define providers for loading user by username and email
        app_user_admin_provider:
            entity:
                class: App\Entity\User
                property: email
        app_user_front_provider:
            entity:
                class: App\Entity\User
                property: email
        app_users:
            chain:
                providers: ['app_user_admin_provider', 'app_user_front_provider']
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Login for regular users
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_front_provider
            json_login:
                check_path: /api/login_check 
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        # Login for admin users
        login1:
            pattern: ^/api/auth/login
            stateless: true
            provider: app_user_admin_provider
            json_login:
                check_path: /api/auth/login_check 
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Default authentication for main users
        main:
            lazy: true
            provider: app_user_admin_provider

        # Protected API endpoints with JWT
        api:  # Correction d'indentation ici
            pattern: ^/api/
            stateless: true
            jwt: ~
            provider: app_users

    # Access control to secure routes
    access_control:
        - { path: ^/api/(login_check|auth/login_check), roles: PUBLIC_ACCESS }
        #- { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

# Configuration pour les tests (hashing faible coût)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
